import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/components/Header";
import { DevValidationStatsHook } from "@/app/components/DevValidationStatsHook";
import { BRAND_NAME } from "@/lib/brand";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: BRAND_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth scroll-pt-14`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <DevValidationStatsHook />
        {/* pt-14 は fixed ヘッダー（h-14 = 56px）の高さ分の余白 */}
        <main className="flex-1 pt-14">{children}</main>
      </body>
    </html>
  );
}
